import './MedicalDataTab.css';
import BasicDataSection from './medical/BasicDataSection';
import DiagnosesSection from './medical/DiagnosesSection';
import MedicalValuesSection from './medical/MedicalValuesSection';
import type { MedicalDataTabProps } from './medical/types';

export default function MedicalDataTab(props: MedicalDataTabProps) {
  const {
    patient,
    editing,
    startEditing,
    saving,
    handleSave,
    cancelEditing,
    form,
    setForm,
    bloodTypes,
    addingDiag,
    setAddingDiag,
    diagCodes,
    diagForm,
    setDiagForm,
    diagSaving,
    handleAddDiag,
    editingDiagId,
    diagEditForm,
    setDiagEditForm,
    handleSaveDiag,
    cancelEditingDiag,
    startEditingDiag,
    confirmDeleteDiagId,
    setConfirmDeleteDiagId,
    handleDeleteDiag,
    formatDate,
    addingMv,
    setAddingMv,
    handleAddAllMv,
    mvSaving,
    sortedMedicalValues,
    toggleMvSort,
    mvSortIndicator,
    editingMvId,
    mvEditForm,
    setMvEditForm,
    mvTemplates,
    renderValueInput,
    resolveDt,
    handleSaveMv,
    cancelEditingMv,
    validateValue,
    confirmDeleteMvId,
    setConfirmDeleteMvId,
    handleDeleteMv,
    startEditingMv,
    mvSortKey,
    mvSortAsc,
    mvDragId,
    mvDragOverId,
    setMvDragId,
    setMvDragOverId,
    handleMvDrop,
    formatValue,
    catalogueCache,
    getCatalogueType,
    mvAddMode,
    setMvAddMode,
    mvForm,
    setMvForm,
    datatypeCodes,
    handleAddMv,
  } = props;

  return (
    <>
      <BasicDataSection
        patient={patient}
        editing={editing}
        startEditing={startEditing}
        saving={saving}
        handleSave={handleSave}
        cancelEditing={cancelEditing}
        form={form}
        setForm={setForm}
        bloodTypes={bloodTypes}
      />

      <DiagnosesSection
        patient={patient}
        addingDiag={addingDiag}
        setAddingDiag={setAddingDiag}
        diagCodes={diagCodes}
        diagForm={diagForm}
        setDiagForm={setDiagForm}
        diagSaving={diagSaving}
        handleAddDiag={handleAddDiag}
        editingDiagId={editingDiagId}
        diagEditForm={diagEditForm}
        setDiagEditForm={setDiagEditForm}
        handleSaveDiag={handleSaveDiag}
        cancelEditingDiag={cancelEditingDiag}
        startEditingDiag={startEditingDiag}
        confirmDeleteDiagId={confirmDeleteDiagId}
        setConfirmDeleteDiagId={setConfirmDeleteDiagId}
        handleDeleteDiag={handleDeleteDiag}
        formatDate={formatDate}
      />

      <MedicalValuesSection
        addingMv={addingMv}
        setAddingMv={setAddingMv}
        handleAddAllMv={handleAddAllMv}
        mvSaving={mvSaving}
        sortedMedicalValues={sortedMedicalValues}
        toggleMvSort={toggleMvSort}
        mvSortIndicator={mvSortIndicator}
        editingMvId={editingMvId}
        mvEditForm={mvEditForm}
        setMvEditForm={setMvEditForm}
        mvTemplates={mvTemplates}
        renderValueInput={renderValueInput}
        resolveDt={resolveDt}
        handleSaveMv={handleSaveMv}
        cancelEditingMv={cancelEditingMv}
        validateValue={validateValue}
        confirmDeleteMvId={confirmDeleteMvId}
        setConfirmDeleteMvId={setConfirmDeleteMvId}
        handleDeleteMv={handleDeleteMv}
        startEditingMv={startEditingMv}
        mvSortKey={mvSortKey}
        mvSortAsc={mvSortAsc}
        mvDragId={mvDragId}
        mvDragOverId={mvDragOverId}
        setMvDragId={setMvDragId}
        setMvDragOverId={setMvDragOverId}
        handleMvDrop={handleMvDrop}
        formatValue={formatValue}
        formatDate={formatDate}
        catalogueCache={catalogueCache}
        getCatalogueType={getCatalogueType}
        mvAddMode={mvAddMode}
        setMvAddMode={setMvAddMode}
        mvForm={mvForm}
        setMvForm={setMvForm}
        datatypeCodes={datatypeCodes}
        handleAddMv={handleAddMv}
      />
    </>
  );
}
