"""Compatibility facade for SQLAlchemy models.

Domain model definitions live under `backend/app/model/`.
This module re-exports them to keep existing imports stable.
"""

from .model import (
    Absence,
    Catalogue,
    AccessPermission,
    Colloqium,
    ColloqiumAgenda,
    ColloqiumParticipant,
    ColloqiumType,
    ColloqiumTypeParticipant,
    Coordination,
    CoordinationDonor,
    CoordinationEpisode,
    CoordinationOrganEffect,
    CoordinationProtocolEventLog,
    CoordinationProcurement,
    CoordinationProcurementFieldScopeTemplate,
    CoordinationProcurementFieldTemplate,
    CoordinationProcurementOrgan,
    CoordinationProcurementSlot,
    CoordinationTimeLog,
    CoordinationProcurementValue,
    CoordinationOrigin,
    Code,
    ContactInfo,
    Diagnosis,
    Episode,
    EpisodeOrgan,
    Favorite,
    Information,
    InformationUser,
    MedicalValue,
    DatatypeDefinition,
    MedicalValueGroup,
    MedicalValueGroupContextTemplate,
    MedicalValueGroupTemplate,
    MedicalValueTemplate,
    MedicalValueTemplateContextTemplate,
    Patient,
    Person,
    PersonTeam,
    Task,
    TaskGroup,
    TaskGroupTemplate,
    TaskTemplate,
    User,
)
from .model.utils import apply_entity_metadata_defaults

# Apply default metadata once after all model classes are imported.
apply_entity_metadata_defaults()

__all__ = [
    "Code",
    "Catalogue",
    "AccessPermission",
    "ColloqiumType",
    "Colloqium",
    "ColloqiumAgenda",
    "ColloqiumTypeParticipant",
    "ColloqiumParticipant",
    "Coordination",
    "CoordinationProtocolEventLog",
    "CoordinationDonor",
    "CoordinationEpisode",
    "CoordinationOrganEffect",
    "CoordinationProcurement",
    "CoordinationProcurementOrgan",
    "CoordinationProcurementSlot",
    "CoordinationProcurementFieldTemplate",
    "CoordinationProcurementFieldScopeTemplate",
    "CoordinationProcurementValue",
    "CoordinationTimeLog",
    "CoordinationOrigin",
    "User",
    "Patient",
    "Person",
    "PersonTeam",
    "Absence",
    "Diagnosis",
    "ContactInfo",
    "MedicalValueTemplate",
    "DatatypeDefinition",
    "MedicalValueGroupTemplate",
    "MedicalValueGroupContextTemplate",
    "MedicalValueGroup",
    "MedicalValue",
    "MedicalValueTemplateContextTemplate",
    "Episode",
    "EpisodeOrgan",
    "Favorite",
    "Information",
    "InformationUser",
    "TaskGroupTemplate",
    "TaskTemplate",
    "TaskGroup",
    "Task",
]




